
service: aws-node-http-api-project

custom:
  stage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      tableName: weather-${self:custom.stage}
    prod:
      tableName: weather-prod
  esbuild:
    exclude: []

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  
  environment:
    DYNAMODB_WEATHER_TABLE: ${self:custom.settings.${self:custom.stage}}-weather
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.settings.${self:custom.stage}}-weather



functions:
  createItem:
    handler: src/createItem.handler
    name: ${self:custom.settings.${self:custom.stage}}-createItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /
          method: post
          cors: true
  getItem:
    handler: src/getItem.handler
    name: ${self:custom.settings.${self:custom.stage}}-getItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{id}
          method: get
          cors: true
  deleteItem:
    handler: src/deleteItem.handler
    name: ${self:custom.settings.${self:custom.stage}}-deleteItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
  updateItem:
    handler: src/updateItem.handler
    name: ${self:custom.settings.${self:custom.stage}}-updateItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{id}
          method: put
          cors: true
  listItems:
    handler: src/listItems.handler
    name: ${self:custom.settings.${self:custom.stage}}-listItems
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /
          method: get
          cors: true

resources:
  Resources:
    WeatherTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.${self:custom.stage}}-weather
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS
          KMSMasterKeyId: alias/aws/dynamodb
        Tags:
          - Key: Name
            Value: ${self:custom.settings.${self:custom.stage}}-weather
          - Key: Stage
            Value: ${sls:stage}