
service: aws-node-http-api-project

provider:
  name: aws
  runtime: nodejs18.x
  
  environment:
    DYNAMODB_WEATHER_TABLE: ${self:service}-${sls:stage}-weather
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-${sls:stage}-weather


functions:
  createItem:
    handler: src/createItem.handler
    name: ${self:service}-${sls:stage}-createItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /
          method: post
          cors: true
  getItem:
    handler: src/getItem.handler
    name: ${self:service}-${sls:stage}-getItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{id}
          method: get
          cors: true
  deleteItem:
    handler: src/deleteItem.handler
    name: ${self:service}-${sls:stage}-deleteItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
  updateItem:
    handler: src/updateItem.handler
    name: ${self:service}-${sls:stage}-updateItem
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /{id}
          method: put
          cors: true
  listItems:
    handler: src/listItems.handler
    name: ${self:service}-${sls:stage}-listItems
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /
          method: get
          cors: true

resources:
  Resources:
    WeatherTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-weather
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS
          KMSMasterKeyId: alias/aws/dynamodb
        Tags:
          - Key: Name
            Value: ${self:service}-${sls:stage}-weather
          - Key: Stage
            Value: ${sls:stage}